name: CI/CD Secure Pipeline

on:
  push:
    branches:
      - main
      - 'release/*'
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Install & Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run lint (placeholder)
        run: npm run lint

      - name: Archive production artifact
        run: |
          mkdir -p artifact
          cp -r src package.json package-lock.json artifact/
          ls -la artifact

  test:
    name: Run tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        env:
          # Variables usadas sólo en el runner. Aquí NO ponemos la API key (test mockea axios).
          NODE_ENV: test
        run: npm test

  deploy:
    name: Deploy (simulated)
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Simulated deploy script
        run: |
          node scripts/simulate-deploy.js
      - name: Upload deploy artifact
        uses: actions/upload-artifact@v4
        with:
          name: deploy-artifact
          path: deploy-artifact.json

# ---- ALTERNATIVA: Despliegue real a Heroku (opcional) ----
# Para usarlo:
# 1) Descomentar la sección de abajo.
# 2) Crear un secret HEROKU_API_KEY con el token de tu cuenta Heroku.
# 3) Crear secret HEROKU_APP_NAME con el nombre de tu app Heroku.
#
# deploy_to_heroku:
#   name: Deploy to Heroku
#   runs-on: ubuntu-latest
#   needs: test
#   if: github.ref == 'refs/heads/main'
#   steps:
#     - name: Checkout
#       uses: actions/checkout@v4
#
#     - name: Setup Node
#       uses: actions/setup-node@v4
#       with:
#         node-version: 18
#
#     - name: Install deps
#       run: npm ci
#
#     - name: Login to Heroku CLI
#       uses: akhileshns/heroku-deploy@v3.12.12
#       with:
#         heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
#         heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
#         heroku_email: ${{ secrets.HEROKU_EMAIL }}
#         usedocker: false
